name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
#Reference: http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/blog/page:num/"

gems:
  - jekyll-sitemap
